% Add the function directory to the path for compilation
addpath('function');

% Compile the application with all required files
mcc -m process_image.m ...
    -a function/dethighlightHZ.m ...
    -a function/KMeans.m ...
    -a function/model.m ...
    -a function/PCANoiseLevelEstimator.m ...
    -R -nodisplay 