name: Update Composer Lock

on:
  workflow_dispatch:

jobs:
  update-composer-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php
      - name: Update composer.lock
        run: php composer.phar update
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update composer.lock
